# hexo-theme-indigo
# https://github.com/yscoder/hexo-theme-indigo

# 添加新菜单项遵循以下规则
# menu:
#  link:               fontawesome图标，省略前缀，本主题前缀为 icon-，必须
#    text: About       菜单显示的文字，如果省略即默认与图标一致，首字母会转大写
#    url: /about       链接，绝对或相对路径，必须。
#    target: _blank    是否跳出，省略则在当前页面打开
menu:
  home:
    text: 主页
    url: /
  archives:
    text: 归档
    url: /archives
  tags:
    text: 标签
    url: /tags
  th-list:
    text: 分类
    url: /categories
  github:
    text: 项目
    url: https://github.com/ystyle
    target: _blank
  weibo:
    text: 微博
    url: http://www.weibo.com/512308314
    target: _blank
  rss:
    text: 订阅
    url: /atom.xml
    target: _blank
  link:
    text: 友链
    url: /friends

rss: /atom.xml

# 你的头像url
avatar: /img/avatar.jpg
# avatar link
avatar_link: /
# 头像背景图
brand: /img/brand.jpg
# favicon
favicon: /img/avatar.jpg

# email
email: lxy5266@live.com

# 设置 Android L Chrome 浏览器状态栏颜色
color: '#3F51B5'

# 页面标题
tags_title: 标签
archives_title: 归档
categories_title: 分类

# 文章截断
excerpt_render: false
excerpt_length: 200
excerpt_link: 阅读全文...
mathjax: true
archive_yearly: true

# 是否显示文章最后更新时间
show_last_updated: true

# 是否开启分享
share: true

# 是否开启打赏，关闭 reward: false
reward: false
#  title: 谢谢大爷~
#  wechat: false     #微信，关闭设为 false
#  alipay: false     #支付宝，关闭设为 false

# 是否开启搜索
search: true

# 是否大屏幕下文章页隐藏导航
hideMenu: false

# 是否开启toc
# toc: false
toc:
  list_number: true  # 是否显示数字排序

# 文章页版权声明内容，hexo中所有变量及辅助函数等均可调用，具体请查阅 hexo.io
postMessage: 本文链接：<a href="<%- url_for(page.path).replace(/index\.html$/, '') %>" target="_blank" rel="external"><%- url.replace(/index\.html$/, '') %></a><br><span>博客内容遵循 <a href="http://creativecommons.org/licenses/by-nc-sa/4.0/" target="_blank">知识共享 署名 - 非商业性 - 相同方式共享 4.0协议</a></span>

# 站长统计，如要开启，输入CNZZ站点id，如 cnzz: 1255152447
cnzz: false

# 百度统计，如要开启，改为你的 key
baidu_tongji: 10658703a526f24446a8cbedef8d287f
baidu_push: true

# 腾讯分析，如要开启，输入站点id
tajs: false

# google
google_analytics: false
google_site_verification: false

# less
less:
  compress: true
  paths:
    - source/css/style.less

# 以下评论插件开启一个即可
# 是否开启 disqus
disqus_shortname: false
# 是否开启友言评论, 填写友言用户id
uyan_uid: false
# 是否使用 gitalk://github.com/gitalk/gitalk
gitalk: 
  owner: ystyle
  repo: ystyle.github.io
  client_id: 1f887c79a8b9b9fbec12
  client_secret: 05033003da5f8a5809b903806420690a665b0ea0

# 规范网址
# 让搜索引擎重定向你的不同域名、不同子域、同域不同目录的站点到你期望的路径
# https://support.google.com/webmasters/answer/139066
# 假设配置为 canonical: http://imys.net，那么从搜索引擎中 www.imys.net 进入会重定向到 imys.net
canonical: false

# 版权起始年份
since_year: 2015

# 用户页面中作者相关的描述性文字，如不需要设为 false
about: Programmers are worthy of respect, the hands of programmers is the magician's hands. <br>They turned boring code into a rich and varied software

# “不蒜子”访问量统计，详见 http://ibruce.info/2015/04/04/busuanzi/
#visit_counter:
#  site_uv: 站点总访客数：
#  site_pv: 站点总访问量：


#动态定义title
title_change:
  normal: 欢迎回来╮(╯▽╰)╭
  leave: 东方星痕的博客
# 设置为 true 发布后将使用 unpkg cdn
cdn: true

# 设置为 true 将使用 lightbox render 图片
lightbox: true

# icp备案号  ICP_license: 京ICP备1234556号-1
ICP_license: false
