name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v2
      - name: 2. setup nodejs...
        uses: actions/setup-node@v2
        with:
          node-version: '7.9.0'
      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm install
      - name: 4. hexo generate public files...
        run: |
          hexo clean
          hexo g
      - name: 5. publish
        uses: heowc/action-hexo@main
        env:
          EMAIL: lxy5266@live.com
          NAME: ystyle
        with:
          args: master
