name: GitHub Actions Build and Deploy
on:
  push:
    branches:
      - hexo

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 1. git checkout...
        uses: actions/checkout@v1
      - name: 2. setup nodejs...
        uses: actions/setup-node@v1
      - name: 3. install hexo...
        run: |
          npm install hexo-cli -g
          npm install
      - name: 4. hexo generate public files...
        run: |
          hexo clean
          hexo g
      - name: 5. publish
        uses: sma11black/hexo-action@v1.0.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          user_name: ystyle
          user_email: lxy5266@live.com
          commit_msg: ${{ github.event.head_commit.message }}
      - name: 6. Refresh Huawei Cloud CDN Cache
        uses: ystyle/hwcdn-cache@master
        env:
          ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
          SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}
          TYPE: directory
          URLS: https://ystyle.top/
